pipeline:
  name: ParentPipelinewADT44Ca3x
  identifier: ParentPipelinewADT44Ca3x
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync
  tags: {}
  stages:
    - stage:
        name: stage1
        identifier: stage1
        type: Pipeline
        spec:
          org: Simlified_Git_sync
          pipeline: pl_auto_pipeline_3krt1
          project: SimplifiedGitSync_Do_Not_Delete