pipeline:
  name: pl_auto_pipeline_WUsmZ
  identifier: pl_auto_pipeline_WUsmZ
  projectIdentifier: CDCNGAuto_CustomWebhookTrigger_BJFmG
  orgIdentifier: DoNotDeleteTriggerOrg
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: stage1
        type: Pipeline
        spec:
          org: DoNotDeleteTriggerOrg
          pipeline: pl_auto_pipeline_YOetm
          project: CDCNGAuto_CustomWebhookTrigger_BJFmG