pipeline:
  name: pl_auto_pipeline_oY8r3
  identifier: pl_auto_pipeline_oY8r3
  projectIdentifier: CDCNGAuto_CustomWebhookTrigger_5DzMF
  orgIdentifier: DoNotDeleteTriggerOrg
  tags: {}
  stages:
    - stage:
        name: WebHook_Trigger
        identifier: WebHook_Trigger
        description: ""
        type: Custom
        spec:
          execution:
            steps:
              - step:
                  type: Http
                  name: WebHook
                  identifier: WebHook
                  spec:
                    url: https://vanilasnapshot.pr2.harness.io/gateway/pipeline/api/webhook/custom/kfB1zdsoTP270kmwU3D3pg/v3?accountIdentifier=NB6rMZhWRL-tpacGdijr2Q&orgIdentifier=DoNotDeleteTriggerOrg&projectIdentifier=CDCNGAuto_CustomWebhookTrigger_5DzMF&pipelineIdentifier=pl_auto_pipeline_6KOIw&triggerIdentifier=CDNGAuto_Trigger_dmdY36UHvR
                    method: POST
                    headers:
                      - key: content-type
                        value: application/json
                      - key: X-HARNESS-TRIGGER-ID
                        value: CDNGAuto_Trigger_dmdY36UHvR
                    outputVariables: []
                    inputVariables: []
                    requestBody: |-
                      {
                          "id": "USA",
                          "locations": [
                              {
                                  "city": "SF"
                              },
                              {
                                  "city": "LV"
                              }
                          ],
                          "name": "user"
                      }
                  timeout: 10m
        tags: {}