pipeline:
  name: pl_auto_pipeline_fQLSt
  identifier: pl_auto_pipeline_fQLSt
  orgIdentifier: DoNotDeleteTriggerOrg
  projectIdentifier: CDCNGAuto_CustomWebhookTrigger_CoH8R
  tags: { }
  stages:
      - stage:
          name: S2
          identifier: S2
          description: ""
          type: Custom
          spec:
            execution:
              steps:
                - step:
                    type: Http
                    name: Http_1
                    identifier: Http_1
                    timeout: 10s
                    spec:
                      url: https://vanilasnapshot.pr2.harness.io/gateway/pipeline/api/webhook/custom/lW0hrVjZTBWUfKYAPNsjYA/v3?accountIdentifier=mlO2egrKSKO3TRlP0yh3CA&orgIdentifier=DoNotDeleteTriggerOrg&projectIdentifier=CDCNGAuto_CustomWebhookTrigger_CoH8R&pipelineIdentifier=pl_auto_pipeline_rQ2Jt&triggerIdentifier=CDNGAuto_Trigger_swXNnvvegF
                      method: POST
                      headers: [ ]
                      inputVariables: [ ]
                      outputVariables: [ ]
                      requestBody: "{\"sample_key\": \"sample_value\"}"
          tags: { }
