pipeline:
  name: remote_multi_svc_env_infra_pipe5h3Up
  identifier: remote_multi_svc_env_infra_pipe5h3Up
  projectIdentifier: NGPipeAutoPipelineSvcXN0Y0IhWvU
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: remote_multi_svc_env_infra_tempNVURR
          versionLabel: v1
          gitBranch: main-patch
