pipeline:
  name: remote_multi_svc_env_infra_pipewzq49
  identifier: remote_multi_svc_env_infra_pipewzq49
  projectIdentifier: NGPipeAutoPipelineSvckXot75Jzlt
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  stages:
    - stage:
        name: s1
        identifier: s1
        tags: {}
        template:
          templateRef: remote_multi_svc_env_infra_tempzDwck
          versionLabel: v1
          gitBranch: main
