pipeline:
    name: Remote55678
    identifier: Remote55678
    projectIdentifier: AmitTest
    orgIdentifier: default
    tags: {}
    stages:
        - stage:
              name: A3
              identifier: A3
              description: dfsee3
              type: Approval
              spec:
                  execution:
                      steps:
                          - step:
                                name: A4
                                identifier: A4
                                type: HarnessApproval
                                timeout: 1d
                                spec:
                                    approvalMessage: |-
                                        Please review the following information
                                        and approve the pipeline progression
                                    includePipelineExecutionHistory: true
                                    approvers:
                                        minimumCount: 1
                                        disallowPipelineExecutor: false
                                        userGroups: <+input>
                                    approverInputs: []
              tags: {}
