service:
  name: NGPipeAutojuMeuTx5rs
  identifier: NGPipeAutojuMeuTx5rs
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcvOxKQKhh4y
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
