environment:
  name: NGPipeAutoIgGSaRltFp
  identifier: NGPipeAutoIgGSaRltFp
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcGwuOAAuUa8
  tags: {
    }
  type: Production
