infrastructureDefinition:
  name: NGPipeAutoqX0EO7T0wL
  identifier: NGPipeAutoqX0EO7T0wL
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoeCkF4BBR2p
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
