environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides3KJwUnQHyY
  identifier: NGPipeAutoHPwefswdAJ
  tags: {}
  name: NGPipeAutoHPwefswdAJ
  type: PreProduction
