environment:
  name: NGPipeAutoOkupMX6NNt
  identifier: NGPipeAutoOkupMX6NNt
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcSPEsw4FZW4
  tags: {
    }
  type: Production
