environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesOVweJBPyDm
  identifier: NGPipeAutoOBh3rcYfAu
  tags: {}
  name: NGPipeAutoOBh3rcYfAu
  type: PreProduction
