service:
  name: NGPipeAutoP5ryUhcI5y
  identifier: NGPipeAutoP5ryUhcI5y
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcO3c9hQJgtB
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
