environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraprXQilTpoY
  identifier: NGPipeAutodDQuZNCaoR
  tags: {}
  name: NGPipeAutodDQuZNCaoR
  type: PreProduction
