service:
  name: NGPipeAutoKyOiPdrY4I
  identifier: NGPipeAutoKyOiPdrY4I
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
