environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcoeP2cPyceh
  identifier: NGPipeAutoelMzNVhEjt
  tags: {}
  name: NGPipeAutoelMzNVhEjt
  type: PreProduction
