environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcq46ZtVl4yf
  identifier: NGPipeAutoDuZ2IgkFWL
  tags: {}
  name: NGPipeAutoDuZ2IgkFWL
  type: PreProduction
