environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesEczRvRdsPm
  identifier: NGPipeAutoX5N7qBbJNt
  tags: {}
  name: NGPipeAutoX5N7qBbJNt
  type: PreProduction
