infrastructureDefinition:
  name: NGPipeAutoMJ0Itaogtt
  identifier: NGPipeAutoMJ0Itaogtt
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraIs6LmOj47a
  environmentRef: NGPipeAutoScmTXw8Qs7
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
