environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides9saU8jjNyH
  identifier: NGPipeAutoxnuc7zEUH2
  tags: {}
  name: NGPipeAutoxnuc7zEUH2
  type: PreProduction
