service:
  name: NGPipeAutoijWoVuQb52
  identifier: NGPipeAutoijWoVuQb52
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
