template:
  name: remote_multi_svc_env_infra_temp7Shbj
  identifier: remote_multi_svc_env_infra_temp7Shbj
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvcEFR0pBmBR8
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvcPq20l92zDM
          - serviceRef: NGPipeAutoSvcxlQm3G8LJz
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutopDjindcpDo
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoIEyo5FuFOu
          - environmentRef: NGPipeAutotJLXqUfx4u
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoPt67D8naPy
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
