template:
  name: NGPipeAutoPipelineTempLb5o2HtSqn
  identifier: NGPipeAutoPipelineTempLb5o2HtSqn
  projectIdentifier: NGPipeAutoPipelineSvcHmKGYRGdzW
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Pipeline
  tags: {}
  spec:
    stages:
      - stage:
          name: s1
          identifier: s1
          tags: {}
          template:
            templateRef: NGPipeAutoStageTemp1xPnZ35QkO
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
      - stage:
          name: s2
          identifier: s2
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempXp31wnBfjj
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                environment:
                  environmentRef: <+input>
                  environmentInputs: <+input>
                  infrastructureDefinitions: <+input>
    allowStageExecutions: true
