environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesPnCh34dlNB
  identifier: NGPipeAutoMfeJOY2SAH
  tags: {}
  name: NGPipeAutoMfeJOY2SAH
  type: PreProduction
