environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrar4LhmGStrm
  identifier: NGPipeAutogRFlDYnNOv
  tags: {}
  name: NGPipeAutogRFlDYnNOv
  type: PreProduction
