environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraAa7CM9bWpi
  identifier: NGPipeAutoGEZZl4RTZs
  tags: {}
  name: NGPipeAutoGEZZl4RTZs
  type: PreProduction
