environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesEwxdGtJi7N
  identifier: NGPipeAutoTkXeHLFyGo
  tags: {}
  name: NGPipeAutoTkXeHLFyGo
  type: PreProduction
