environment:
  name: NGPipeAutoCtFOORLazx
  identifier: NGPipeAutoCtFOORLazx
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc8qcnj3Vo7a
  tags: {
    }
  type: Production
