infrastructureDefinition:
  name: NGPipeAutoOGj8gBmY6I
  identifier: NGPipeAutoOGj8gBmY6I
  environmentRef: NGPipeAuto6YVMjq7YbO
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
