environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrax6N2YdvH40
  identifier: NGPipeAutoWNhos8I2Of
  tags: {}
  name: NGPipeAutoWNhos8I2Of
  type: PreProduction
