infrastructureDefinition:
  name: NGPipeAutoPxPMqB8roD
  identifier: NGPipeAutoPxPMqB8roD
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfralX3lUGgbRz
  environmentRef: NGPipeAutoJr77CYw1rZ
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
