environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcj8AhLAwbIN
  identifier: NGPipeAutoHknR1uOTIt
  tags: {}
  name: NGPipeAutoHknR1uOTIt
  type: PreProduction
