environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcrqna8nXxQD
  identifier: NGPipeAuto0tzRoFxHx8
  tags: {}
  name: NGPipeAuto0tzRoFxHx8
  type: PreProduction
