environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesFyQDQJm1YU
  identifier: NGPipeAutocybwuOHmUN
  tags: {}
  name: NGPipeAutocybwuOHmUN
  type: PreProduction
