environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvckSW2ohcC4L
  identifier: NGPipeAuto93Rm5enDmt
  tags: {}
  name: NGPipeAuto93Rm5enDmt
  type: PreProduction
