infrastructureDefinition:
  name: NGPipeAutoUzbFIKJ6HI
  identifier: NGPipeAutoUzbFIKJ6HI
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc9UIhJzwBze
  environmentRef: NGPipeAutolJPPWF6yXD
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
