service:
  name: NGPipeAutosTk1NwmijQ
  identifier: NGPipeAutosTk1NwmijQ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
