infrastructureDefinition:
  name: NGPipeAutok98b8p8GXh
  identifier: NGPipeAutok98b8p8GXh
  environmentRef: NGPipeAutomIA3ZQU9Pa
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
