environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraSH8RtmLfkL
  identifier: NGPipeAutoQilSmQzCAl
  tags: {}
  name: NGPipeAutoQilSmQzCAl
  type: PreProduction
