infrastructureDefinition:
  name: NGPipeAutoBKkVuK0cN5
  identifier: NGPipeAutoBKkVuK0cN5
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra1lj1XxB8Jp
  environmentRef: NGPipeAutoaaDLHPDY8H
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
