environment:
  name: NGPipeAutoP9JcVqbapE
  identifier: NGPipeAutoP9JcVqbapE
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvccxLvyd8Hgs
  tags: {
    }
  type: Production
