environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesGXmFXUvPgH
  identifier: NGPipeAuto4eLe6UTRsQ
  tags: {}
  name: NGPipeAuto4eLe6UTRsQ
  type: PreProduction
