environment:
  name: NGPipeAutoB2bXLaHGdR
  identifier: NGPipeAutoB2bXLaHGdR
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcfRBQs4DAqP
  tags: {
    }
  type: Production
