environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrayd7cRRHuRN
  identifier: NGPipeAuto1TfHpPFIAS
  tags: {}
  name: NGPipeAuto1TfHpPFIAS
  type: PreProduction
