template:
  name: NGPipeAutoStepTempLkIo9P5Zzm
  identifier: NGPipeAutoStepTempLkIo9P5Zzm
  projectIdentifier: NGPipeAutoPipelineSvc4bndE4IV70
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: <+input>
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
