environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcaHbAcgG6po
  identifier: NGPipeAutoqz6q9cemUr
  tags: {}
  name: NGPipeAutoqz6q9cemUr
  type: PreProduction
