environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides4fRY4jYHTT
  identifier: NGPipeAutoz8V3Sq2Bh3
  tags: {}
  name: NGPipeAutoz8V3Sq2Bh3
  type: PreProduction
