environment:
  name: NGPipeAutoj4ooUecqGk
  identifier: NGPipeAutoj4ooUecqGk
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcGfgWUNeai2
  tags: {
    }
  type: Production
