environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcdxcAXRlilA
  identifier: NGPipeAutosKTlBfdk3W
  tags: {}
  name: NGPipeAutosKTlBfdk3W
  type: PreProduction
