service:
  name: NGPipeAutoSvcVQwaVUd7iS
  identifier: NGPipeAutoSvcVQwaVUd7iS
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvclYdSAwz9a6
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
