environment:
  name: NGPipeAutoTqdpKL9FcO
  identifier: NGPipeAutoTqdpKL9FcO
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcpU7AY5EDTP
  tags: {
    }
  type: Production
