pipeline:
  name: NGPipeAutoNGPipelinek4RY1jA48P
  identifier: NGPipeAutoNGPipelinek4RY1jA48P
  projectIdentifier: NGPipeAutoPipelineSvcVTyuCYWs35
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  tags: {}
  template:
    templateRef: NGPipeAutoPipelineTemp4SwRwk28Tt
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Custom
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Custom
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
