environment:
  name: NGPipeAutoyvg1M9kmZy
  identifier: NGPipeAutoyvg1M9kmZy
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvckehlk133uq
  tags: {
    }
  type: Production
