service:
  name: NGPipeAutoEveroW0Y45
  identifier: NGPipeAutoEveroW0Y45
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvci3X01lxaub
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
