service:
  name: NGPipeAutoJhOpxyow8n
  identifier: NGPipeAutoJhOpxyow8n
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc35jCQSXaoO
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
