infrastructureDefinition:
  name: NGPipeAutoD8UBppRAZO
  identifier: NGPipeAutoD8UBppRAZO
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra2dd5RhWnS2
  environmentRef: NGPipeAutouq5HyhJkDw
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
