environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcMJn1JXgom2
  identifier: NGPipeAutojcNxeJFLzG
  tags: {}
  name: NGPipeAutojcNxeJFLzG
  type: PreProduction
