environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc8uESiy9FyQ
  identifier: NGPipeAutoKGlsvlXHLx
  tags: {}
  name: NGPipeAutoKGlsvlXHLx
  type: PreProduction
