environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcAmIyYb20bM
  identifier: NGPipeAutoNLLJjOuaO3
  tags: {}
  name: NGPipeAutoNLLJjOuaO3
  type: PreProduction
