environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcCRga6prrEM
  identifier: NGPipeAutovUcuQMYUdg
  tags: {}
  name: NGPipeAutovUcuQMYUdg
  type: PreProduction
