environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrao89ihM52rO
  identifier: NGPipeAutoW7LDzE5GuE
  tags: {}
  name: NGPipeAutoW7LDzE5GuE
  type: PreProduction
