infrastructureDefinition:
  name: NGPipeAuto0PdqXFtS4m
  identifier: NGPipeAuto0PdqXFtS4m
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraaS849S40Vb
  environmentRef: NGPipeAutoDYYYuYzZCI
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
