service:
  name: NGPipeAutok9RYtsEDSv
  identifier: NGPipeAutok9RYtsEDSv
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvclyIumCCZ89
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
