environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcaUXYkDei46
  identifier: NGPipeAutoZ8Wvji0l02
  tags: {}
  name: NGPipeAutoZ8Wvji0l02
  type: PreProduction
