environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc1ehbZlJm4W
  identifier: NGPipeAutoqpQrYk8jcC
  tags: {}
  name: NGPipeAutoqpQrYk8jcC
  type: PreProduction
