environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcm1zyL1YFij
  identifier: NGPipeAutoUVps26cFYl
  tags: {}
  name: NGPipeAutoUVps26cFYl
  type: PreProduction
