template:
  name: remote_multi_svc_env_infra_tempvMXns
  identifier: remote_multi_svc_env_infra_tempvMXns
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvc4En6KDYgAy
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvcWLLucdrJY1
          - serviceRef: NGPipeAutoSvc2K7MDSc36Z
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutoxu4ToKjbsQ
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoFV1vkDN4pj
          - environmentRef: NGPipeAutoTYhOMCALi5
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAuto0CuOHEYRlM
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
