environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcoeP2cPyceh
  identifier: NGPipeAutoEJvOgAHoey
  tags: {}
  name: NGPipeAutoEJvOgAHoey
  type: PreProduction
