environment:
  name: NGPipeAutoeDfx5Sh8vN
  identifier: NGPipeAutoeDfx5Sh8vN
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvctwKKDY1i0s
  tags: {
    }
  type: Production
