environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesTFAIBs6AQG
  identifier: NGPipeAuto4q5FkZtXgK
  tags: {}
  name: NGPipeAuto4q5FkZtXgK
  type: PreProduction
