service:
  name: NGPipeAutob6Gix443Ry
  identifier: NGPipeAutob6Gix443Ry
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcbBzgjJRm0F
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
