environment:
  name: NGPipeAutoOitfzqoXUo
  identifier: NGPipeAutoOitfzqoXUo
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc6vjWGbnJay
  tags: {
    }
  type: Production
