environment:
  name: NGPipeAutoWP6YcbJ2F4
  identifier: NGPipeAutoWP6YcbJ2F4
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcR4CjyhzeTS
  tags: {
    }
  type: Production
