infrastructureDefinition:
  name: NGPipeAutoYZtgQU8gmy
  identifier: NGPipeAutoYZtgQU8gmy
  environmentRef: NGPipeAutoitC1GMqcww
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
