environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesaKD5a9eKeN
  identifier: NGPipeAutojTGnjHSJ3G
  tags: {}
  name: NGPipeAutojTGnjHSJ3G
  type: PreProduction
