environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesGVFPNZ0p9o
  identifier: NGPipeAutoC6hW1p9CMN
  tags: {}
  name: NGPipeAutoC6hW1p9CMN
  type: PreProduction
