environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcYvTxKJByKM
  identifier: NGPipeAutoxY8w6f3Yn7
  tags: {}
  name: NGPipeAutoxY8w6f3Yn7
  type: PreProduction
