environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraXSTw9FlWnL
  identifier: NGPipeAuto0t6VPmhTt1
  tags: {}
  name: NGPipeAuto0t6VPmhTt1
  type: PreProduction
