environment:
  name: NGPipeAutoSTRoAzMEzU
  identifier: NGPipeAutoSTRoAzMEzU
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcUQ9bdvxyOi
  tags: {
    }
  type: Production
