environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc40s8vWYHBG
  identifier: NGPipeAutoEcNZg0giEB
  tags: {}
  name: NGPipeAutoEcNZg0giEB
  type: PreProduction
