environment:
  name: NGPipeAutokHVs4Sf6Sc
  identifier: NGPipeAutokHVs4Sf6Sc
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcY0oYdbiSsK
  tags: {
    }
  type: Production
