infrastructureDefinition:
  name: NGPipeAutogUPWWVihVX
  identifier: NGPipeAutogUPWWVihVX
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcxdIh7SdGYK
  environmentRef: NGPipeAuto9wDAdoWPep
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
