service:
  name: NGPipeAutos3YNDgUbB3
  identifier: NGPipeAutos3YNDgUbB3
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcNtY7g8uYXD
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
