service:
  name: NGPipeAutoUFQOX5yK4V
  identifier: NGPipeAutoUFQOX5yK4V
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcrnFWcvwY6U
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
