environment:
  name: NGPipeAutovk6eBWC5QI
  identifier: NGPipeAutovk6eBWC5QI
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc2O56vMHT7I
  tags: {
    }
  type: Production
