environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra3PfB8eYy90
  identifier: NGPipeAutoqn1IteCyaC
  tags: {}
  name: NGPipeAutoqn1IteCyaC
  type: PreProduction
