environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridescn767bDnsF
  identifier: NGPipeAutod5ZrFShJMv
  tags: {}
  name: NGPipeAutod5ZrFShJMv
  type: PreProduction
