environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrau0sA9RUKt9
  identifier: NGPipeAutoO80XRk2Tab
  tags: {}
  name: NGPipeAutoO80XRk2Tab
  type: PreProduction
