infrastructureDefinition:
  name: NGPipeAutoi7VaFJhTx9
  identifier: NGPipeAutoi7VaFJhTx9
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutogxjGRkez0O
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
