infrastructureDefinition:
  name: NGPipeAuto1C9G3cwxRs
  identifier: NGPipeAuto1C9G3cwxRs
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoObjSoh2tKC
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
