environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfralX3lUGgbRz
  identifier: NGPipeAutoDd1KJWoALH
  tags: {}
  name: NGPipeAutoDd1KJWoALH
  type: PreProduction
