service:
  name: NGPipeAutoaWpOMV2QXv
  identifier: NGPipeAutoaWpOMV2QXv
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcGHYAsONV03
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
