environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcjvvrizCbwk
  identifier: NGPipeAutoZ2pFj4sWCE
  tags: {}
  name: NGPipeAutoZ2pFj4sWCE
  type: PreProduction
