environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraDYIo7mxtmF
  identifier: NGPipeAuto84E9N9hMlQ
  tags: {}
  name: NGPipeAuto84E9N9hMlQ
  type: PreProduction
