environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesVn9p7I25Wz
  identifier: NGPipeAuto0e8kIO8d2y
  tags: {}
  name: NGPipeAuto0e8kIO8d2y
  type: PreProduction
