environment:
  name: NGPipeAutokBgdqSUOd0
  identifier: NGPipeAutokBgdqSUOd0
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcjxqOwlFVSh
  tags: {
    }
  type: Production
