environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraYJq2tFncVq
  identifier: NGPipeAutopfdTBltPuV
  tags: {}
  name: NGPipeAutopfdTBltPuV
  type: PreProduction
