environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcZW6yxsRs8f
  identifier: NGPipeAutol7GK2Cuvt4
  tags: {}
  name: NGPipeAutol7GK2Cuvt4
  type: PreProduction
