environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrasj3zD6IP29
  identifier: NGPipeAutouRxvKm7JZD
  tags: {}
  name: NGPipeAutouRxvKm7JZD
  type: PreProduction
