service:
  name: NGPipeAuto03toxVCcAJ
  identifier: NGPipeAuto03toxVCcAJ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcq3Ciw5Os9h
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
