infrastructureDefinition:
  name: NGPipeAutoDBueA2XNoZ
  identifier: NGPipeAutoDBueA2XNoZ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraocLohYGKlz
  environmentRef: NGPipeAuto3xpKWif46t
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
