environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra0QepRd5Qxh
  identifier: NGPipeAutohXnZusrVyz
  tags: {}
  name: NGPipeAutohXnZusrVyz
  type: PreProduction
