environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraU7yjH4tX60
  identifier: NGPipeAutoRqCvAenkuh
  tags: {}
  name: NGPipeAutoRqCvAenkuh
  type: PreProduction
