service:
  name: NGPipeAutouj6c25lSKN
  identifier: NGPipeAutouj6c25lSKN
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcxCTUWf3F91
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
