environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvchWoWnj1EgR
  identifier: NGPipeAutoxR1XPjZqcU
  tags: {}
  name: NGPipeAutoxR1XPjZqcU
  type: PreProduction
