environment:
  name: NGPipeAutoCKN2hWhYYZ
  identifier: NGPipeAutoCKN2hWhYYZ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcDvXA7XZeLQ
  tags: {
    }
  type: Production
