infrastructureDefinition:
  name: NGPipeAutoh03KbPvxbD
  identifier: NGPipeAutoh03KbPvxbD
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutox9Uc5ZFXtC
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
