environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcoeP2cPyceh
  identifier: NGPipeAutoPGzGmSAq8c
  tags: {}
  name: NGPipeAutoPGzGmSAq8c
  type: PreProduction
