environment:
  name: NGPipeAuto3dDEnEJnni
  identifier: NGPipeAuto3dDEnEJnni
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcpyvS2tZ6ZH
  tags: {
    }
  type: Production
