environment:
  name: NGPipeAutovrW0Dr24BH
  identifier: NGPipeAutovrW0Dr24BH
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcfRBQs4DAqP
  tags: {
    }
  type: Production
