infrastructureDefinition:
  name: NGPipeAutodW6Sp5wJoI
  identifier: NGPipeAutodW6Sp5wJoI
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrawLjwLNBf5E
  environmentRef: NGPipeAutouZMKzpgTrr
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
