service:
  name: NGPipeAutoSvc47Pd5EaCZ7
  identifier: NGPipeAutoSvc47Pd5EaCZ7
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcryXee7tx6i
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
