infrastructureDefinition:
  name: NGPipeAutoiCTVph7mQz
  identifier: NGPipeAutoiCTVph7mQz
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoqCCjZcFKX0
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
