environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcnLdj4NQzNm
  identifier: NGPipeAuto4bEvA9g4x1
  tags: {}
  name: NGPipeAuto4bEvA9g4x1
  type: PreProduction
