environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides6LTASPxIAf
  identifier: NGPipeAutoaX0gpYt2uz
  tags: {}
  name: NGPipeAutoaX0gpYt2uz
  type: PreProduction
