environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridessagsIqB6Pc
  identifier: NGPipeAutolDqsWWXlBQ
  tags: {}
  name: NGPipeAutolDqsWWXlBQ
  type: PreProduction
