environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesw12UHRz3xq
  identifier: NGPipeAutoaZmbujQ7x2
  tags: {}
  name: NGPipeAutoaZmbujQ7x2
  type: PreProduction
