environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesWshgxJYZUB
  identifier: NGPipeAutoyWQtWEL8D4
  tags: {}
  name: NGPipeAutoyWQtWEL8D4
  type: PreProduction
