environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcnvYoPHR0A0
  identifier: NGPipeAutoJ1gzGgj86Y
  tags: {}
  name: NGPipeAutoJ1gzGgj86Y
  type: PreProduction
