environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrideseLO7PycD8k
  identifier: NGPipeAutopRKHan7bpI
  tags: {}
  name: NGPipeAutopRKHan7bpI
  type: PreProduction
