environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcpyvS2tZ6ZH
  identifier: NGPipeAutoCYI92WutH0
  tags: {}
  name: NGPipeAutoCYI92WutH0
  type: PreProduction
