service:
  name: NGPipeAutoSvcTwHNNI7jib
  identifier: NGPipeAutoSvcTwHNNI7jib
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvccZ3bJcnD1W
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
