environment:
  name: NGPipeAutoLlPmup9IOZ
  identifier: NGPipeAutoLlPmup9IOZ
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcR6FGEpUd3N
  tags: {
    }
  type: Production
