infrastructureDefinition:
  name: NGPipeAutoSU79FlPYK6
  identifier: NGPipeAutoSU79FlPYK6
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoaYXyAF1cfz
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
