environment:
  name: NGPipeAuto9IuUtJ2L0u
  identifier: NGPipeAuto9IuUtJ2L0u
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcrADmS4xWer
  tags: {
    }
  type: Production
