environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcryXee7tx6i
  identifier: NGPipeAutokoX9Ynq7P3
  tags: {}
  name: NGPipeAutokoX9Ynq7P3
  type: PreProduction
