environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc6d7b4DlLtd
  identifier: NGPipeAutoCuDoyURtcz
  tags: {}
  name: NGPipeAutoCuDoyURtcz
  type: PreProduction
