environment:
  name: NGPipeAutoBIzSJWE0Fx
  identifier: NGPipeAutoBIzSJWE0Fx
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcUJX3v9IIhg
  tags: {
    }
  type: Production
