infrastructureDefinition:
  name: NGPipeAutoTf7FTW5Xvb
  identifier: NGPipeAutoTf7FTW5Xvb
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcFpCGcrYWeK
  environmentRef: NGPipeAutoKL6ZVBDdKU
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
