environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvckPwoqNu9y3
  identifier: NGPipeAutoMCmHhkdTD8
  tags: {}
  name: NGPipeAutoMCmHhkdTD8
  type: PreProduction
