environment:
  name: NGPipeAutopS1JtkELQi
  identifier: NGPipeAutopS1JtkELQi
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcCz3Bzlmg2a
  tags: {
    }
  type: Production
