infrastructureDefinition:
  name: NGPipeAuto3Y5Jh5IKGa
  identifier: NGPipeAuto3Y5Jh5IKGa
  environmentRef: NGPipeAuto1ct7wHhPpg
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
