environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra96CZEfHP8j
  identifier: NGPipeAutoMgYKWupupm
  tags: {}
  name: NGPipeAutoMgYKWupupm
  type: PreProduction
