template:
  name: NGPipeAutoStepTempA1FIlQJd2b
  identifier: NGPipeAutoStepTempA1FIlQJd2b
  projectIdentifier: NGPipeAutoPipelineSvc7Nsfzas64C
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Step
  tags: {}
  spec:
    timeout: <+input>
    type: ShellScript
    spec:
      shell: Bash
      onDelegate: true
      source:
        type: Inline
        spec:
          script: echo Hello
      environmentVariables: []
      outputVariables: []
