infrastructureDefinition:
  name: NGPipeAutoTiWaWOY4Ok
  identifier: NGPipeAutoTiWaWOY4Ok
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAuto5o0QD1rILg
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
