infrastructureDefinition:
  name: NGPipeAutoBhh8Xl1CKR
  identifier: NGPipeAutoBhh8Xl1CKR
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoI4rdW1ehxj
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
