environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVlKw6hPH1a
  identifier: NGPipeAutovSHG9ZjVmZ
  tags: {}
  name: NGPipeAutovSHG9ZjVmZ
  type: PreProduction
