environment:
  name: NGPipeAutoz56yxZAgQ1
  identifier: NGPipeAutoz56yxZAgQ1
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcjxqOwlFVSh
  tags: {
    }
  type: Production
