environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcb9k5SC3rGq
  identifier: NGPipeAutoSz00yksnUN
  tags: {}
  name: NGPipeAutoSz00yksnUN
  type: PreProduction
