service:
  name: NGPipeAuto5rvwspc9sy
  identifier: NGPipeAuto5rvwspc9sy
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
