environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvck2H4TqTD3P
  identifier: NGPipeAutoccqY27IrFq
  tags: {}
  name: NGPipeAutoccqY27IrFq
  type: PreProduction
