environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcOR7ypGst7b
  identifier: NGPipeAutoOl2Osb8Qrh
  tags: {}
  name: NGPipeAutoOl2Osb8Qrh
  type: PreProduction
