environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra892XiDPneK
  identifier: NGPipeAuto0BV2ui6woH
  tags: {}
  name: NGPipeAuto0BV2ui6woH
  type: PreProduction
