environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcxdIh7SdGYK
  identifier: NGPipeAutomtd4vTETny
  tags: {}
  name: NGPipeAutomtd4vTETny
  type: PreProduction
