infrastructureDefinition:
  name: NGPipeAutoYJ1kEUdul8
  identifier: NGPipeAutoYJ1kEUdul8
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfracnEAbjZzKJ
  environmentRef: NGPipeAutoQc4qzrMEDT
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
