environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrajipzzN5c5O
  identifier: NGPipeAutohObAvG4J90
  tags: {}
  name: NGPipeAutohObAvG4J90
  type: PreProduction
