infrastructureDefinition:
  name: NGPipeAutoSaWE6ebPCy
  identifier: NGPipeAutoSaWE6ebPCy
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrahUACBl4hX1
  environmentRef: NGPipeAutoaZFS31gwtz
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
