environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides2bbUqnQC6q
  identifier: NGPipeAutoGVmf5VQMKR
  tags: {}
  name: NGPipeAutoGVmf5VQMKR
  type: PreProduction
