environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcKYeNbdbRz2
  identifier: NGPipeAutoGAwoCm9FBm
  tags: {}
  name: NGPipeAutoGAwoCm9FBm
  type: PreProduction
