environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesdejlijtwv4
  identifier: NGPipeAutoxhLWRyUckA
  tags: {}
  name: NGPipeAutoxhLWRyUckA
  type: PreProduction
