environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcFWEVham3YQ
  identifier: NGPipeAutoyuzl5N2PCm
  tags: {}
  name: NGPipeAutoyuzl5N2PCm
  type: PreProduction
