environment:
  name: NGPipeAutoSoEKOfhVdR
  identifier: NGPipeAutoSoEKOfhVdR
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcDvXA7XZeLQ
  tags: {
    }
  type: Production
