template:
  name: NGPipeAutoPipelineTemp7RVmj2kAl8
  identifier: NGPipeAutoPipelineTemp7RVmj2kAl8
  projectIdentifier: NGPipeAutoPipelineSvcFghDXfZSwM
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  type: Pipeline
  tags: {}
  spec:
    stages:
      - stage:
          name: s1
          identifier: s1
          tags: {}
          template:
            templateRef: NGPipeAutoStageTempuyrfvdaogb
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                execution:
                  steps:
                    - step:
                        identifier: step1
                        template:
                          templateInputs:
                            type: ShellScript
                            timeout: <+input>
      - stage:
          name: s2
          identifier: s2
          tags: {}
          template:
            templateRef: NGPipeAutoStageTemp26IqLXWJUM
            versionLabel: v1
            templateInputs:
              type: Custom
              spec:
                execution:
                  steps:
                    - step:
                        identifier: step2
                        template:
                          templateInputs:
                            type: ShellScript
                            timeout: <+input>
    allowStageExecutions: true

