environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides09I6yMsozu
  identifier: NGPipeAutogLLnoIYwgz
  tags: {}
  name: NGPipeAutogLLnoIYwgz
  type: PreProduction
