environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides27gsdQr7mZ
  identifier: NGPipeAutoqvuYJLQHjj
  tags: {}
  name: NGPipeAutoqvuYJLQHjj
  type: PreProduction
