environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrahWZF1VqB4T
  identifier: NGPipeAutoLnlY6oFQQR
  tags: {}
  name: NGPipeAutoLnlY6oFQQR
  type: PreProduction
