environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesUURH0xg8nl
  identifier: NGPipeAutoFeVP2bPhz4
  tags: {}
  name: NGPipeAutoFeVP2bPhz4
  type: PreProduction
