environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesImym5Eh56a
  identifier: NGPipeAutoBkTDDF0EDh
  tags: {}
  name: NGPipeAutoBkTDDF0EDh
  type: PreProduction
