infrastructureDefinition:
  name: NGPipeAuto8mkvvFIoNB
  identifier: NGPipeAuto8mkvvFIoNB
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoJnM4cSXjtc
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
