environment:
  name: NGPipeAutog6hRmZ0SNf
  identifier: NGPipeAutog6hRmZ0SNf
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcPxanm6QlGN
  tags: {
    }
  type: Production
