environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvckehlk133uq
  identifier: NGPipeAutoReOTP3eEt8
  tags: {}
  name: NGPipeAutoReOTP3eEt8
  type: PreProduction
