service:
  name: NGPipeAutoSvcfHdCe2V8Do
  identifier: NGPipeAutoSvcfHdCe2V8Do
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcJdpQQnxQb6
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
