infrastructureDefinition:
  name: NGPipeAutovY6t6Dj8zP
  identifier: NGPipeAutovY6t6Dj8zP
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoZGK2lckZmT
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
