environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesvVLlqfEFIz
  identifier: NGPipeAutokBtLhL2Q7V
  tags: {}
  name: NGPipeAutokBtLhL2Q7V
  type: PreProduction
