environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraqKgSYcbFSU
  identifier: NGPipeAutofjn3BNEx68
  tags: {}
  name: NGPipeAutofjn3BNEx68
  type: PreProduction
