service:
  name: NGPipeAuto1nK9VZ4ucc
  identifier: NGPipeAuto1nK9VZ4ucc
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvco5gzGUqsyi
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
