infrastructureDefinition:
  name: NGPipeAutoQphrLmPGzX
  identifier: NGPipeAutoQphrLmPGzX
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvct1rjeqRgd0
  environmentRef: NGPipeAutozXnshHtI6o
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
