environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcBHjS05sHWD
  identifier: NGPipeAutoNJDGQfeFW2
  tags: {}
  name: NGPipeAutoNJDGQfeFW2
  type: PreProduction
