environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvck4mpePoZyo
  identifier: NGPipeAuto5ZfV19Onog
  tags: {}
  name: NGPipeAuto5ZfV19Onog
  type: PreProduction
