environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra9mWcqeK6qu
  identifier: NGPipeAutogNVG2c7z7y
  tags: {}
  name: NGPipeAutogNVG2c7z7y
  type: PreProduction
