infrastructureDefinition:
  name: NGPipeAutoQ74UKR0dcn
  identifier: NGPipeAutoQ74UKR0dcn
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutokyOzWXHrAj
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
