environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcA4Ub9c2mQT
  identifier: NGPipeAutoWwbfWcY75t
  tags: {}
  name: NGPipeAutoWwbfWcY75t
  type: PreProduction
