environment:
  name: NGPipeAutot9Efd7o9Jd
  identifier: NGPipeAutot9Efd7o9Jd
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcMJn1JXgom2
  tags: {
    }
  type: Production
