infrastructureDefinition:
  name: NGPipeAutom7nwYmXRZL
  identifier: NGPipeAutom7nwYmXRZL
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraEoZN5sT6fT
  environmentRef: NGPipeAuto0Wl6eysUtO
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
