service:
  name: NGPipeAutoq6UKfBr0W0
  identifier: NGPipeAutoq6UKfBr0W0
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc94iPMratL9
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
