environment:
  name: NGPipeAuto1sPu1mSR0x
  identifier: NGPipeAuto1sPu1mSR0x
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcM2ppfJE2wO
  tags: {
    }
  type: Production
