environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridescpszskxAFr
  identifier: NGPipeAuto90vdeVNgjn
  tags: {}
  name: NGPipeAuto90vdeVNgjn
  type: PreProduction
