environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcoeP2cPyceh
  identifier: NGPipeAutoDcSMuijAwL
  tags: {}
  name: NGPipeAutoDcSMuijAwL
  type: PreProduction
