environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvck2H4TqTD3P
  identifier: NGPipeAutowaAdaOoMbp
  tags: {}
  name: NGPipeAutowaAdaOoMbp
  type: PreProduction
