infrastructureDefinition:
  name: NGPipeAutorEOFeM9F6k
  identifier: NGPipeAutorEOFeM9F6k
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraDLqIvzjZ9Y
  environmentRef: NGPipeAuto2LfFWf3deA
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
