service:
  name: NGPipeAutofRvvNTe7tR
  identifier: NGPipeAutofRvvNTe7tR
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcFCDIpepUO3
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
