environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraRo66tfR05A
  identifier: NGPipeAutoJYuWO4GU5H
  tags: {}
  name: NGPipeAutoJYuWO4GU5H
  type: PreProduction
