environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides8EtDFNi6pp
  identifier: NGPipeAutoKD5kFzsaAq
  tags: {}
  name: NGPipeAutoKD5kFzsaAq
  type: PreProduction
