service:
  name: NGPipeAutobOTOrhXNe8
  identifier: NGPipeAutobOTOrhXNe8
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
