infrastructureDefinition:
  name: NGPipeAuto1Uh6fr2g3w
  identifier: NGPipeAuto1Uh6fr2g3w
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoj3sQMLK2u7
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
