service:
  name: NGPipeAutoW5N6wzGDfo
  identifier: NGPipeAutoW5N6wzGDfo
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
