environment:
  name: NGPipeAutoKGlsvlXHLx
  identifier: NGPipeAutoKGlsvlXHLx
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc8uESiy9FyQ
  tags: {
    }
  type: Production
