environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra6QwM6TzmIH
  identifier: NGPipeAutoSkfTRXOWKf
  tags: {}
  name: NGPipeAutoSkfTRXOWKf
  type: PreProduction
