infrastructureDefinition:
  name: NGPipeAutoZkS6XdNyt6
  identifier: NGPipeAutoZkS6XdNyt6
  environmentRef: NGPipeAutoxV6shrzQ0t
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
