infrastructureDefinition:
  name: NGPipeAutoUw4rfuvIu0
  identifier: NGPipeAutoUw4rfuvIu0
  environmentRef: NGPipeAutok0J6NDYJX5
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
