environment:
  name: NGPipeAutoRyVezABh4x
  identifier: NGPipeAutoRyVezABh4x
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcC2qb8yjHy0
  tags: {
    }
  type: Production
