environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraIJlVu0id9n
  identifier: NGPipeAuto8PEx9LK6En
  tags: {}
  name: NGPipeAuto8PEx9LK6En
  type: PreProduction
