environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides6CfaTf8dXi
  identifier: NGPipeAutoblBtVKgHco
  tags: {}
  name: NGPipeAutoblBtVKgHco
  type: PreProduction
