environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcMJn1JXgom2
  identifier: NGPipeAutot9Efd7o9Jd
  tags: {}
  name: NGPipeAutot9Efd7o9Jd
  type: PreProduction
