infrastructureDefinition:
  name: NGPipeAutoE3mHaeYhnD
  identifier: NGPipeAutoE3mHaeYhnD
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrayU8a6V3GGf
  environmentRef: NGPipeAuto8MCYfT0tsz
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
