infrastructureDefinition:
  name: NGPipeAutoDyGeIyNYtE
  identifier: NGPipeAutoDyGeIyNYtE
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra8Ou9VjvkXa
  environmentRef: NGPipeAuto2phfA8Ggkw
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
