environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesjLGZ2HOYs1
  identifier: NGPipeAuto7mORcFf3wx
  tags: {}
  name: NGPipeAuto7mORcFf3wx
  type: PreProduction
