environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraFXSolBUlfh
  identifier: NGPipeAuto9jyNciDhLm
  tags: {}
  name: NGPipeAuto9jyNciDhLm
  type: PreProduction
