environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides25ieUBsJGV
  identifier: NGPipeAuto6HsuagK6to
  tags: {}
  name: NGPipeAuto6HsuagK6to
  type: PreProduction
