environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesk4Gnbj9NBg
  identifier: NGPipeAutojPgW2xNUBk
  tags: {}
  name: NGPipeAutojPgW2xNUBk
  type: PreProduction
