template:
  name: remote_multi_svc_env_infra_temp9hQfh
  identifier: remote_multi_svc_env_infra_temp9hQfh
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvcKSti6Vyjrf
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvcxrLMMfl8Xn
          - serviceRef: NGPipeAutoSvcRKjOeLPaMW
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutoNEERbHnRL0
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoEBkTfQ7oQo
          - environmentRef: NGPipeAuto7IRXh9rmoG
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutoCUIV63cUkX
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
