environment:
  name: NGPipeAutoCYI92WutH0
  identifier: NGPipeAutoCYI92WutH0
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcpyvS2tZ6ZH
  tags: {
    }
  type: Production
