environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesiU0hUKlZAC
  identifier: NGPipeAutopSQF1DZ9Ix
  tags: {}
  name: NGPipeAutopSQF1DZ9Ix
  type: PreProduction
