environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcGfgWUNeai2
  identifier: NGPipeAutotPdznUyoCe
  tags: {}
  name: NGPipeAutotPdznUyoCe
  type: PreProduction
