environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcA14X8t45qB
  identifier: NGPipeAutogw6PcCxOW8
  tags: {}
  name: NGPipeAutogw6PcCxOW8
  type: PreProduction
