service:
  name: NGPipeAutonfOblE2PIC
  identifier: NGPipeAutonfOblE2PIC
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
