environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc5SoRiMwpUb
  identifier: NGPipeAutogu5EXNnWVU
  tags: {}
  name: NGPipeAutogu5EXNnWVU
  type: PreProduction
