environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesYTvjyigCdl
  identifier: NGPipeAutouRu0vm7Adt
  tags: {}
  name: NGPipeAutouRu0vm7Adt
  type: PreProduction
