environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraifYTiWYzKV
  identifier: NGPipeAuto54lo5UFWdc
  tags: {}
  name: NGPipeAuto54lo5UFWdc
  type: PreProduction
