infrastructureDefinition:
  name: NGPipeAutoEF1qlhUi3I
  identifier: NGPipeAutoEF1qlhUi3I
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc1UdimaInMn
  environmentRef: NGPipeAutoNRTP1nAzWV
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
