environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcdYfEplufJm
  identifier: NGPipeAutopAQvHvsGA3
  tags: {}
  name: NGPipeAutopAQvHvsGA3
  type: PreProduction
