environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrao9rPcrozhU
  identifier: NGPipeAuto5oZqcc3Dni
  tags: {}
  name: NGPipeAuto5oZqcc3Dni
  type: PreProduction
