environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcxs5UcFLYsz
  identifier: NGPipeAuto4W3tQxM2N0
  tags: {}
  name: NGPipeAuto4W3tQxM2N0
  type: PreProduction
