environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesunc1OMzfG5
  identifier: NGPipeAutoVrxYz5cY87
  tags: {}
  name: NGPipeAutoVrxYz5cY87
  type: PreProduction
