environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwbhwTUcn4t
  identifier: NGPipeAutoPxbYRjUFWW
  tags: {}
  name: NGPipeAutoPxbYRjUFWW
  type: PreProduction
