infrastructureDefinition:
  name: NGPipeAutoeaQtyjNrVc
  identifier: NGPipeAutoeaQtyjNrVc
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraTA2UaNx6cp
  environmentRef: NGPipeAutofpwtxuTS1Q
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
