environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcAFCGLJMG4F
  identifier: NGPipeAutoOk4EyRwB3b
  tags: {}
  name: NGPipeAutoOk4EyRwB3b
  type: PreProduction
