infrastructureDefinition:
  name: NGPipeAutoH9t7Q8HrlY
  identifier: NGPipeAutoH9t7Q8HrlY
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoC28DiMUysp
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
