environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcIa4hJjw5zc
  identifier: NGPipeAuto4T2OgoPHqm
  tags: {}
  name: NGPipeAuto4T2OgoPHqm
  type: PreProduction
