environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridescDp1huIcWs
  identifier: NGPipeAutoyBDlTFQZ0K
  tags: {}
  name: NGPipeAutoyBDlTFQZ0K
  type: PreProduction
