environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcLQP7I9hKM7
  identifier: NGPipeAutoHLi7dhn954
  tags: {}
  name: NGPipeAutoHLi7dhn954
  type: PreProduction
