environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesjLGZ2HOYs1
  identifier: NGPipeAuto5k0xqH8j2Q
  tags: {}
  name: NGPipeAuto5k0xqH8j2Q
  type: PreProduction
