pipeline:
  name: NGPipeAutoNGPipelineRNUxza4V17
  identifier: NGPipeAutoNGPipelineRNUxza4V17
  projectIdentifier: NGPipeAutoPipelineSvcFghDXfZSwM
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  tags: {}
  template:
    templateRef: NGPipeAutoPipelineTempm32PjP9PXP
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: step1
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Custom
                spec:
                  execution:
                    steps:
                      - step:
                          identifier: step2
                          template:
                            templateInputs:
                              type: ShellScript
                              timeout: <+input>
