infrastructureDefinition:
  name: NGPipeAutodXooPryVFN
  identifier: NGPipeAutodXooPryVFN
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraRo66tfR05A
  environmentRef: NGPipeAutoJYuWO4GU5H
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
