environment:
  name: NGPipeAutockpmZbvKuo
  identifier: NGPipeAutockpmZbvKuo
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcPB60JvJzgB
  tags: {
    }
  type: Production
