environment:
  name: NGPipeAutoYhTv7UIfwV
  identifier: NGPipeAutoYhTv7UIfwV
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcwJFEsf1USe
  tags: {
    }
  type: Production
