environment:
  name: NGPipeAutoD4z43bZnIz
  identifier: NGPipeAutoD4z43bZnIz
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcliGi7PPgvY
  tags: {
    }
  type: Production
