infrastructureDefinition:
  name: NGPipeAutobUHke6hqD8
  identifier: NGPipeAutobUHke6hqD8
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAuto4AnitQzPee
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
