environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides6EmF2ZWLNy
  identifier: NGPipeAuto0qvxSCV31f
  tags: {}
  name: NGPipeAuto0qvxSCV31f
  type: PreProduction
