environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides66QpZ74yIs
  identifier: NGPipeAutoe810aemoad
  tags: {}
  name: NGPipeAutoe810aemoad
  type: PreProduction
