infrastructureDefinition:
  name: NGPipeAuto1aWV9SBkyK
  identifier: NGPipeAuto1aWV9SBkyK
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraWEtgPrlnyH
  environmentRef: NGPipeAutoMT2YdeEQM1
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
