environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraZ9H9QoTQPE
  identifier: NGPipeAutoSUN6pFbo1z
  tags: {}
  name: NGPipeAutoSUN6pFbo1z
  type: PreProduction
