environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvct1rjeqRgd0
  identifier: NGPipeAutozXnshHtI6o
  tags: {}
  name: NGPipeAutozXnshHtI6o
  type: PreProduction
