environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc22QT3MUMiT
  identifier: NGPipeAutouJFz1XqQiI
  tags: {}
  name: NGPipeAutouJFz1XqQiI
  type: PreProduction
