environment:
  name: NGPipeAutouhFx8MqYAn
  identifier: NGPipeAutouhFx8MqYAn
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc1xGyTeFE62
  tags: {
    }
  type: Production
