environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcdYfEplufJm
  identifier: NGPipeAutoRTaG4vRHSO
  tags: {}
  name: NGPipeAutoRTaG4vRHSO
  type: PreProduction
