infrastructureDefinition:
  name: NGPipeAuto19ZJO8lMXS
  identifier: NGPipeAuto19ZJO8lMXS
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra3JZxPzuwbL
  environmentRef: NGPipeAutotQmuhnnFcI
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
