environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesYWPiaL6nJI
  identifier: NGPipeAutoFSZZUAwqx9
  tags: {}
  name: NGPipeAutoFSZZUAwqx9
  type: PreProduction
