environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesVfXVF2XOgZ
  identifier: NGPipeAuto9LGtlvNkis
  tags: {}
  name: NGPipeAuto9LGtlvNkis
  type: PreProduction
