infrastructureDefinition:
  name: NGPipeAutoHkUZeZFpTD
  identifier: NGPipeAutoHkUZeZFpTD
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoJHQzEFJ0Uo
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
