environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraSFzwBVuUyk
  identifier: NGPipeAuto8WgeBdlioE
  tags: {}
  name: NGPipeAuto8WgeBdlioE
  type: PreProduction
