environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraVQaipKA2Nw
  identifier: NGPipeAutown5oM0vZ7v
  tags: {}
  name: NGPipeAutown5oM0vZ7v
  type: PreProduction
