environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcY0oYdbiSsK
  identifier: NGPipeAutoxXFlWoz4VD
  tags: {}
  name: NGPipeAutoxXFlWoz4VD
  type: PreProduction
