service:
  name: NGPipeAutogBTek7V5bC
  identifier: NGPipeAutogBTek7V5bC
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcJueIK7VbUu
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
