environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraWv8p2rxZ6e
  identifier: NGPipeAutoljE14HgBe8
  tags: {}
  name: NGPipeAutoljE14HgBe8
  type: PreProduction
