environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesPBzvares4g
  identifier: NGPipeAutoSTo4y1gx80
  tags: {}
  name: NGPipeAutoSTo4y1gx80
  type: PreProduction
