service:
  name: NGPipeAutoyFABQgF6Zw
  identifier: NGPipeAutoyFABQgF6Zw
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcMeQtqJkWoW
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
