environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcm1ntmuP9oQ
  identifier: NGPipeAutoDe5pQuyqEx
  tags: {}
  name: NGPipeAutoDe5pQuyqEx
  type: PreProduction
