environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraUW5a7Cayj4
  identifier: NGPipeAutoKab2z0Cn7L
  tags: {}
  name: NGPipeAutoKab2z0Cn7L
  type: PreProduction
