environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVfJ2aVyEVP
  identifier: NGPipeAuto7lw3Cpuwcg
  tags: {}
  name: NGPipeAuto7lw3Cpuwcg
  type: PreProduction
