environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvc1xGyTeFE62
  identifier: NGPipeAutony7BvTSQpC
  tags: {}
  name: NGPipeAutony7BvTSQpC
  type: PreProduction
