environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcaHbAcgG6po
  identifier: NGPipeAutoHwmHNxc5mI
  tags: {}
  name: NGPipeAutoHwmHNxc5mI
  type: PreProduction
