environment:
  name: NGPipeAuto1LUt8kPlaA
  identifier: NGPipeAuto1LUt8kPlaA
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcSpHrqpgYNI
  tags: {
    }
  type: Production
