environment:
  name: NGPipeAutog1FSmFpN4v
  identifier: NGPipeAutog1FSmFpN4v
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcYFRVW3BFid
  tags: {
    }
  type: Production
