environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesxI0WqUplMO
  identifier: NGPipeAutovUsbkkPRGe
  tags: {}
  name: NGPipeAutovUsbkkPRGe
  type: PreProduction
