service:
  name: NGPipeAutoSvcEoZKEtBoAU
  identifier: NGPipeAutoSvcEoZKEtBoAU
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcFpCGcrYWeK
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
