service:
  name: NGPipeAutotAr7rlssFt
  identifier: NGPipeAutotAr7rlssFt
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
