infrastructureDefinition:
  name: NGPipeAuto1wgO5w5fOP
  identifier: NGPipeAuto1wgO5w5fOP
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoThazj1sTDq
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: <+input>
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
