environment:
  name: NGPipeAutoxWLvTE6ANK
  identifier: NGPipeAutoxWLvTE6ANK
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqSlmsnR9oL
  tags: {
    }
  type: Production
