environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcN36MvICQfY
  identifier: NGPipeAutoZ9QoNgEurJ
  tags: {}
  name: NGPipeAutoZ9QoNgEurJ
  type: PreProduction
