environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraPX2pon4ztN
  identifier: NGPipeAutoXP6gcBymYc
  tags: {}
  name: NGPipeAutoXP6gcBymYc
  type: PreProduction
