environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra2dd5RhWnS2
  identifier: NGPipeAutouq5HyhJkDw
  tags: {}
  name: NGPipeAutouq5HyhJkDw
  type: PreProduction
