environment:
  name: NGPipeAutoCg3JLJmx4i
  identifier: NGPipeAutoCg3JLJmx4i
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcB5mnMQZtRm
  tags: {
    }
  type: Production
