service:
  name: NGPipeAutoSvc7QPbgTaYOV
  identifier: NGPipeAutoSvc7QPbgTaYOV
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcryXee7tx6i
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
