environment:
  name: NGPipeAuto9gw94gOFX5
  identifier: NGPipeAuto9gw94gOFX5
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcWuDLNWaY3t
  tags: {
    }
  type: Production
