infrastructureDefinition:
  name: NGPipeAutoqumS4DVuyx
  identifier: NGPipeAutoqumS4DVuyx
  orgIdentifier: Pipelines_NonK8s_Org_NG
  environmentRef: NGPipeAutoxW54hp4DDt
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: account.github_Account_level_connector_delegate
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
