service:
  name: NGPipeAutoSvcmrG07R3roP
  identifier: NGPipeAutoSvcmrG07R3roP
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcxzBSG6pWaA
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
