environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesnzhdcTKz9d
  identifier: NGPipeAuto3Azgx6KGCF
  tags: {}
  name: NGPipeAuto3Azgx6KGCF
  type: PreProduction
