environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfral2E0F7UKqk
  identifier: NGPipeAutonioACf1rWr
  tags: {}
  name: NGPipeAutonioACf1rWr
  type: PreProduction
