pipeline:
  name: NGPipeAutoNGPipelinejD8UOHNI0s
  identifier: NGPipeAutoNGPipelinejD8UOHNI0s
  projectIdentifier: NGPipeAutoPipelineSvc3CZgpeiCMy
  orgIdentifier: Pipelines_NonK8s_Org_NG
  versionLabel: v1
  tags: {}
  template:
    templateRef: NGPipeAutoPipelineTempJnn26c2Pkn
    versionLabel: v1
    templateInputs:
      stages:
        - stage:
            identifier: s1
            template:
              templateInputs:
                type: Custom
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
        - stage:
            identifier: s2
            template:
              templateInputs:
                type: Custom
                spec:
                  environment:
                    environmentRef: <+input>
                    environmentInputs: <+input>
                    infrastructureDefinitions: <+input>
