environment:
  name: NGPipeAuto2QhtnZFZqE
  identifier: NGPipeAuto2QhtnZFZqE
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvceQmuA5i9Nm
  tags: {
    }
  type: Production
