service:
  name: NGPipeAuto3dbgS9TboA
  identifier: NGPipeAuto3dbgS9TboA
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
