environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra1k0eKxTghB
  identifier: NGPipeAutoPs0i8vc5Ml
  tags: {}
  name: NGPipeAutoPs0i8vc5Ml
  type: PreProduction
