environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcaIRbZ8TG0i
  identifier: NGPipeAutoA711ZWpbnd
  tags: {}
  name: NGPipeAutoA711ZWpbnd
  type: PreProduction
