environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesWshgxJYZUB
  identifier: NGPipeAutohXvyU4PEEP
  tags: {}
  name: NGPipeAutohXvyU4PEEP
  type: PreProduction
