environment:
  name: NGPipeAutoF63L2nvpXK
  identifier: NGPipeAutoF63L2nvpXK
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcVrSiZ2zmMY
  tags: {
    }
  type: Production
