environment:
  name: NGPipeAutoueAWgM5TTu
  identifier: NGPipeAutoueAWgM5TTu
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcbdmjX7x3m0
  tags: {
    }
  type: Production
