environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcWEbj3h0MNf
  identifier: NGPipeAutokudXodK5Cl
  tags: {}
  name: NGPipeAutokudXodK5Cl
  type: PreProduction
