infrastructureDefinition:
  name: NGPipeAutoUVA9ub7rKd
  identifier: NGPipeAutoUVA9ub7rKd
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcWjFOuqYpmj
  environmentRef: NGPipeAutoKPro63eHQO
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
