environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcqvqwvUDaJO
  identifier: NGPipeAutojAxP1xJP0n
  tags: {}
  name: NGPipeAutojAxP1xJP0n
  type: PreProduction
