environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrides00YA4JhY1i
  identifier: NGPipeAuto0e7UszaQEV
  tags: {}
  name: NGPipeAuto0e7UszaQEV
  type: PreProduction
