environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfralX3lUGgbRz
  identifier: NGPipeAutoJr77CYw1rZ
  tags: {}
  name: NGPipeAutoJr77CYw1rZ
  type: PreProduction
