environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesDq74yzKD4N
  identifier: NGPipeAuto2Xk6xBgngj
  tags: {}
  name: NGPipeAuto2Xk6xBgngj
  type: PreProduction
