environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcSz91ikCzsH
  identifier: NGPipeAutouEjPey8z78
  tags: {}
  name: NGPipeAutouEjPey8z78
  type: PreProduction
