infrastructureDefinition:
  name: NGPipeAutoe5SOFSTrvs
  identifier: NGPipeAutoe5SOFSTrvs
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvck4mpePoZyo
  environmentRef: NGPipeAutoeGh1J47t89
  deploymentType: Kubernetes
  type: KubernetesDirect
  spec:
    connectorRef: org.KubernetesConnectorForAutomationTest
    namespace: default
    releaseName: release-<+INFRA_KEY_SHORT_ID>
  allowSimultaneousDeployments: true
