environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra5NwVIunEjZ
  identifier: NGPipeAutoYrNR9kFMSV
  tags: {}
  name: NGPipeAutoYrNR9kFMSV
  type: PreProduction
