environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcMyjDCxql0Q
  identifier: NGPipeAutoUP2sEH4CNg
  tags: {}
  name: NGPipeAutoUP2sEH4CNg
  type: PreProduction
