environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfrawrwQWmz7B4
  identifier: NGPipeAutoCnXYYJXyWQ
  tags: {}
  name: NGPipeAutoCnXYYJXyWQ
  type: PreProduction
