service:
  name: NGPipeAutoPf5OANRL8I
  identifier: NGPipeAutoPf5OANRL8I
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcE5FUrHoINk
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
