service:
  name: NGPipeAutoZkF6TYQpR8
  identifier: NGPipeAutoZkF6TYQpR8
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
