environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcNJyFLRnA26
  identifier: NGPipeAutoaXBvktX85H
  tags: {}
  name: NGPipeAutoaXBvktX85H
  type: PreProduction
