service:
  name: NGPipeAutobmw9otiYrG
  identifier: NGPipeAutobmw9otiYrG
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
