environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverridesq1XyaTfq6W
  identifier: NGPipeAutoiHpnFwVjJ4
  tags: {}
  name: NGPipeAutoiHpnFwVjJ4
  type: PreProduction
