environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraySZs9ACleR
  identifier: NGPipeAutouIEpEZlkPx
  tags: {}
  name: NGPipeAutouIEpEZlkPx
  type: PreProduction
