environment:
  name: NGPipeAutoo3iv0Qwnkn
  identifier: NGPipeAutoo3iv0Qwnkn
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcJWHSS9yoKb
  tags: {
    }
  type: Production
