environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcm1ntmuP9oQ
  identifier: NGPipeAutovGNrppnAmm
  tags: {}
  name: NGPipeAutovGNrppnAmm
  type: PreProduction
