service:
  name: NGPipeAutoUeQHb4hz3d
  identifier: NGPipeAutoUeQHb4hz3d
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvceixftZ9Swb
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
