environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcjnTdAdpkJd
  identifier: NGPipeAutorygdWRl5Kd
  tags: {}
  name: NGPipeAutorygdWRl5Kd
  type: PreProduction
