environment:
  name: NGPipeAuto3mX30FOi7z
  identifier: NGPipeAuto3mX30FOi7z
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvclKvprEiLiM
  tags: {
    }
  type: Production
