environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcI7Voszn2Hm
  identifier: NGPipeAuto6UN0FZtaPS
  tags: {}
  name: NGPipeAuto6UN0FZtaPS
  type: PreProduction
