environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvci1hHqmOwke
  identifier: NGPipeAuto791OQrQQKM
  tags: {}
  name: NGPipeAuto791OQrQQKM
  type: PreProduction
