environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfra4YW5VFHaU4
  identifier: NGPipeAutorPOJ312f3H
  tags: {}
  name: NGPipeAutorPOJ312f3H
  type: PreProduction
