service:
  name: NGPipeAutof3nmzPyfRo
  identifier: NGPipeAutof3nmzPyfRo
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcGRlrrRUw6Q
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
