environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineOverrideslgbwhqZPkQ
  identifier: NGPipeAutoZGsFFuKkfF
  tags: {}
  name: NGPipeAutoZGsFFuKkfF
  type: PreProduction
