service:
  name: NGPipeAutoSvc4tWYWy77nl
  identifier: NGPipeAutoSvc4tWYWy77nl
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvct1rjeqRgd0
  serviceDefinition:
    spec:
      release:
        name: <+input>
    type: Kubernetes
