template:
  name: remote_multi_svc_env_infra_tempzDwck
  identifier: remote_multi_svc_env_infra_tempzDwck
  versionLabel: v1
  type: Stage
  projectIdentifier: NGPipeAutoPipelineSvckXot75Jzlt
  orgIdentifier: Pipelines_NonK8s_Org_NG
  tags: {}
  spec:
    type: Deployment
    spec:
      deploymentType: Kubernetes
      execution:
        steps:
          - step:
              type: ShellScript
              name: ShellScript_1
              identifier: ShellScript_1
              spec:
                shell: Bash
                executionTarget: {}
                source:
                  type: Inline
                  spec:
                    script: echo "hi"
                environmentVariables: []
                outputVariables: []
              timeout: 10m
        rollbackSteps: []
      services:
        values:
          - serviceRef: NGPipeAutoSvcA11xnhJfJC
          - serviceRef: NGPipeAutoSvcMEPtBsi63g
        metadata:
          parallel: true
      environments:
        metadata:
          parallel: true
        values:
          - environmentRef: NGPipeAutoAw3SX7ZVmx
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutobWkP9eVghI
          - environmentRef: NGPipeAutopVyH2nbrh4
            deployToAll: false
            infrastructureDefinitions:
              - identifier: NGPipeAutou92YWQDiqQ
    failureStrategies:
      - onFailure:
          errors:
            - AllErrors
          action:
            type: MarkAsFailure
