service:
  name: NGPipeAuto1T5A7CuCz9
  identifier: NGPipeAuto1T5A7CuCz9
  orgIdentifier: Pipelines_NonK8s_Org_NG
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
