environment:
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineInfraYJq2tFncVq
  identifier: NGPipeAuto6E0U1NPTM2
  tags: {}
  name: NGPipeAuto6E0U1NPTM2
  type: PreProduction
