service:
  name: NGPipeAutotMj9NPU6ZL
  identifier: NGPipeAutotMj9NPU6ZL
  orgIdentifier: Pipelines_NonK8s_Org_NG
  projectIdentifier: NGPipeAutoPipelineSvcGv0ZcGZ11k
  serviceDefinition:
    spec:
      release:
        name: release-<+INFRA_KEY_SHORT_ID>
    type: Kubernetes
