pipeline:
  name: pl_auto_pipeline_VV4NR
  identifier: pl_auto_pipeline_VV4NR
  template:
    templateRef: account.pl_auto_pipeline_IaaDw
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync