pipeline:
  name: pl_auto_pipeline_fhe5D
  identifier: pl_auto_pipeline_fhe5D
  template:
    templateRef: account.pl_auto_pipeline_hrZwq
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync