pipeline:
  name: pl_auto_pipeline_I2jnL
  identifier: pl_auto_pipeline_I2jnL
  template:
    templateRef: account.pl_auto_pipeline_JIf4r
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync