pipeline:
  name: pl_auto_pipeline_0Xu5r
  identifier: pl_auto_pipeline_0Xu5r
  template:
    templateRef: account.pl_auto_pipeline_Wp0TA
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync