pipeline:
  name: pl_auto_pipeline_CeI5n
  identifier: pl_auto_pipeline_CeI5n
  template:
    templateRef: account.pl_auto_pipeline_IWS1C
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync