pipeline:
  name: pl_auto_pipeline_SXZuY
  identifier: pl_auto_pipeline_SXZuY
  template:
    templateRef: account.pl_auto_pipeline_Nkch5
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync