pipeline:
  name: pl_auto_pipeline_IcN7k
  identifier: pl_auto_pipeline_IcN7k
  template:
    templateRef: account.pl_auto_pipeline_0b0BL
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync