pipeline:
  name: pl_auto_pipeline_gWj1Z
  identifier: pl_auto_pipeline_gWj1Z
  template:
    templateRef: account.pl_auto_pipeline_TkQCj
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync