pipeline:
  name: pl_auto_pipeline_uwy2T
  identifier: pl_auto_pipeline_uwy2T
  template:
    templateRef: account.pl_auto_pipeline_ZwLMC
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync