pipeline:
  name: pl_auto_pipeline_N5zSH
  identifier: pl_auto_pipeline_N5zSH
  template:
    templateRef: account.pl_auto_pipeline_cYoEY
    versionLabel: v3
  tags: { }
  projectIdentifier: SimplifiedGitSync_Do_Not_Delete
  orgIdentifier: Simlified_Git_sync