pipeline:
  name: pl_auto_pipeline_6ndzx
  identifier: pl_auto_pipeline_6ndzx
  template:
    templateRef: account.pl_auto_template_Msw6k
    versionLabel: v3
    templateInputs:
      stages:
        - stage:
            identifier: q1
            type: Approval
            spec:
              execution:
                steps:
                  - step:
                      identifier: a1
                      type: HarnessApproval
                      spec:
                        approvers:
                          userGroups: <+input>
  tags: { }
  projectIdentifier: NGPipeAutoWebHookNotificationgbPJosztYw
  orgIdentifier: Simlified_Git_sync